obj-y := dev2devfs.o dev2devfs_glue_helper.o fcntl.o kmalloc.o \
	pmm.o schedule.o timer.o uaccess.o ucore_stat2linux_stat.o irq.o kthread.o workqueue.o timer_helper.o kthread_helper.o wait_helper.o

obj-y += idr.o scatterlist.o

obj-$(UCONFIG_ARM_BOARD_GOLDFISH) += arm_iomap_glue.o
obj-$(UCONFIG_ARM_BOARD_PANDABOARD) += arm_iomap_glue.o
