dirs-y := debug driver init libs mm numa process syscall trap kmodule

dirs-$(UCONFIG_ARM_BOARD_GOLDFISH) += mach-goldfish
dirs-$(UCONFIG_ARM_BOARD_RASPBERRYPI) += mach-raspberrypi
dirs-$(UCONFIG_ARM_BOARD_PANDABOARD) += mach-pandaboard
