dirs-y := debug driver init libs mm process syscall trap module

dirs-$(UCONFIG_ARM_BOARD_GOLDFISH) += mach-goldfish
dirs-$(UCONFIG_ARM_BOARD_RASPBERRYPI) += mach-raspberrypi
dirs-$(UCONFIG_ARM_BOARD_PANDABOARD) += mach-pandaboard
