obj-y := yaffs_allocator.o yaffs_attribs.o yaffs_bitmap.o yaffs_checkptrw.o \
		yaffs_ecc.o yaffs_error.o yaffs_guts.o yaffs_hweight.o \
		yaffs_nameval.o yaffs_nand.o yaffs_nandif.o yaffs_osglue.o \
		yaffs_packedtags1.o yaffs_packedtags2.o yaffs_qsort.o \
		yaffs_summary.o yaffs_tagscompat.o yaffs_verify.o yaffs_vfs.o \
		yaffs_yaffs1.o yaffs_yaffs2.o yaffsfs.o 

obj-y += mtd_glue.o
obj-$(UCONFIG_HAVE_YAFFS2_RAMDISK) += yramsim.o
