#dirs-y := fs libs mm process  schedule sync syscall
#dirs-y += arch/$(ARCH)

#dirs-$(UCONFIG_LINUX_DDE_BASE) += module
dirs-y := schedule syscall fs process mm libs glue-ucore sync kmodule

dirs-y += arch/$(ARCH)

dirs-$(UCONFIG_HAVE_LINUX_DDE_BASE) += module
