# Makefile for the Linux device tree

obj-y			:= core.o sys.o bus.o dd.o \
			   driver.o class.o platform.o \
			   init.o map.o devres.o \
			   attribute_container.o transport_class.o

obj-y	+= dma-mapping.o
obj-y	+= module.o

